### PR TITLE
Angular16

### PR DESCRIPTION
**Pull request by ducthang-vu**
Update to Angular16.

### CODE REVIEW

**Comment by ducthang-vu** [comment]
@maykon-oliveira May I ask you, if the PR is fine, to bump the version and publish in NPM registry?

**Comment by ducthang-vu** [comment]
@maykon-oliveira Have you had time to check this pr?

**Comment by maykon-oliveira** [comment]
@ducthang-vu  Sorry for my late. I'll check it.

**Comment by ducthang-vu** [comment]
> @ducthang-vu Sorry for my late. I'll check it.

No problem! Is it possibile to bump the version and publish?

**Pull request merged**
